### ISSUE TITLE
Failed to download after Few Videos.

### ISSUE THREAD

**Issue by Babadook007** [RahulShaw/LinuxAcademy-DL#12]
First.. Thanks a bunch for making it work!

Worked Great till First 60 Videos.. Past that it started failing...

Cleared All Cookies.. Re-Fetched Cookies in cookies.txt. . Let Chromium fetch new cookies.. Still no difference -

[generic] 280: Requesting header
WARNING: Forcing on generic information extractor.
[generic] 280: Downloading webpage
[generic] 280: Extracting information
[download] Sleeping 15 seconds...
ERROR: unable to download video data: HTTP Error 400: Bad Request
ERROR: unable to download video data: HTTP Error 400: Bad Request
Downloading failed. Perhaps, the cookies have expired.

**Comment by RahulShaw** [comment]
Please update the `youtube-dl` package and that will fix the problem.
`pip install youtube-dl --upgrade`
