### ISSUE TITLE
The same video is repeatedly downloaded

### ISSUE THREAD

**Issue by techguyj** [RahulShaw/LinuxAcademy-DL#16]
This worked on August 4th and now suddenly stopped working. Tested from multiple computers.
[PowerShell_transcript.qfpEhXoA.20190806132901.txt](https://github.com/RahulShaw/LinuxAcademy-DL/files/3471724/PowerShell_transcript.qfpEhXoA.20190806132901.txt)

```
$ ll -lah
total 61M
drwxr-xr-x 1 user 197121   0 Aug  6 13:32  ./
drwxr-xr-x 1 user 197121   0 Aug  6 13:30  ../
-rw-r--r-- 1 user 197121 21M Aug  6 13:31 '1. About the Course Author.mp4'
-rw-r--r-- 1 user 197121 21M Aug  6 13:31 '2. How to Use the Linux Academy Cloud Playground for this Course.mp4'
-rw-r--r-- 1 user 197121 21M Aug  6 13:32 '3. Course `Syllabus.mp4'
```

**Comment by newtrojan** [comment]
I think something changed on linux academy website

**Comment by satrox28** [comment]
will it be fixed soon?. I am also facing the same issue.

**Comment by RahulShaw** [comment]
Currently, I do not have an active LinuxAcademy subscription. If someone can voluntarily share their subscription with me, I shall work on the issues/requests. I'm sorry :(

**Comment by newtrojan** [comment]
> Currently, I do not have an active LinuxAcademy subscription. If someone can voluntarily share their subscription with me, I shall work on the issues/requests. I'm sorry :(

Is there a way to send  a PM

**Comment by RahulShaw** [comment]
You may 

> > Currently, I do not have an active LinuxAcademy subscription. If someone can voluntarily share their subscription with me, I shall work on the issues/requests. I'm sorry :(
> 
> Is there a way to send a PM

You may reach me here https://www.facebook.com/TheRahulShaw

**Comment by hila3000** [comment]
I'm facing this issue as well.
@RahulShaw I've sent you a message on facebook, please check.

**Comment by RahulShaw** [comment]
Please update the `youtube-dl` package and that will fix the problem.
`pip install youtube-dl --upgrade`
