### ISSUE TITLE
Issue downloading a specific course

### ISSUE THREAD

**Issue by hila3000** [RahulShaw/LinuxAcademy-DL#18]
Hi,

I have no issue downloading other courses.
only this course download results with an error after login-

c:\LinuxAcademy-DL>python driver.py username password https://linuxacademy.com/cp/modules/view/id/329
Requesting download of https://linuxacademy.com/cp/modules/view/id/329

DevTools listening on ws://127.0.0.1:50484/devtools/browser/676648bd-9a64-4a5a-b3be-ceebc8b221f9
[2072:15088:0914/204138.485:ERROR:browser_process_sub_thread.cc(203)] Waited 319 ms for network service
Sleeping for 45 seconds..
Attempting to login..
Login successful...
Getting lesson links...
Traceback (most recent call last):
  File "driver.py", line 85, in <module>
    title = parsed_html.find('span', attrs={'class', 'course-title'}).text
AttributeError: 'NoneType' object has no attribute 'text'

Please advise.

**Comment by RahulShaw** [comment]
I hope this is fixed now! 😊

**Comment by RahulShaw** [comment]
I hope this is fixed now! 😊
