### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by honeyriar** [RahulShaw/LinuxAcademy-DL#23]
Hi, I'm getting this issue everytime I run driver.py on line 85. 
"Login successful...
Getting lesson links...
Traceback (most recent call last):
  File "driver.py", line 85, in <module>
    title = parsed_html.find('span', attrs={'class', 'course-title'}).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by RahulShaw** [comment]
This has been fixed in the latest commit.
