### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by rajcspsg** [RahulShaw/LinuxAcademy-DL#3]
$ sudo python3 driver.py user_id password https://linuxacademy.com/cp/modules/view/id/327
Requesting download of https://linuxacademy.com/cp/modules/view/id/327
Darwin
Sleeping for 15 seconds..
Attempting to login..
Login successful...
Getting lesson links...
Traceback (most recent call last):
  File "driver.py", line 88, in <module>
    title = parsed_html.find('span', attrs={'class', 'course-title'}).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by amitfegade121** [comment]
Hi,
    Try the below commands and download again.
 
    >pip install selenium
 
    >pip install beautifulsoup4

    I am downloading other course now, once I  finished this, I will try to download your course and will let you know whether its a same problem for me or not.

**Comment by rajcspsg** [comment]
@amitfegade121 see I'm using python3 here. Is that correct?

**Comment by RahulShaw** [comment]
@rajcspsg - I tried downloading the course https://linuxacademy.com/cp/modules/view/id/327 and it worked for me. Strangely it does not work for you. 

- Can you share a screenshot of the page (from the browser) when the script halts with an exception ?

- Do you have an active LinuxAcademy subscription ?

**Comment by thomas-wolf** [comment]
@rajcspsg : Maybe you have an active schedule for your course? Had the same issue. Then I tried deleting my schedule (you can do this in "manage this schedule" menu) and everything went fine.

**Comment by rajcspsg** [comment]
@thomas-wolf I don't know what is the issue with my mac. I created fedora VM and it worked there.
I'm closing this issue.
