### ISSUE TITLE
Downloads are too slow

### ISSUE THREAD

**Issue by manuareraa** [RahulShaw/LinuxAcademy-DL#30]
I don't know if this is the actual speed in which this tool downloads. But my Internet speed is capable of downloading more than 20GB per day. But LinuxAcademy Tool downloads only 5-6GB per day. Sometimes I believe that the download times is actually the duration o course. Because AWS Cert prep course is 33 Hrs long and while I am typing this , the download is going on for 18+ hours now. Still hasn't finished. I don't know why this is so slow.

**Comment by RahulShaw** [comment]
I've tested this tool thoroughly and can testify that the tool does not throttle download speeds. It's either your ISP or Linux Academy.

**Comment by manuareraa** [comment]
> I've tested this tool thoroughly and can testify that the tool does not throttle download speeds. It's either your ISP or Linux Academy.

I am a beginner in coding. I would like to know how to transfer those "Urls" which end with "chunklist" to a external text file. I want the complete urls[ ] list to be tansfered. I tried writing it to a text file, but didn't work. Can you help me, please ?
