### ISSUE TITLE
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

### ISSUE THREAD

**Issue by lyricnz** [RahulShaw/LinuxAcademy-DL#33]
After pip install -r requirements.txt still get error. Need to install html5lib module? Not mentioned in README.

```
~ Logged in! ~
Getting lesson links...
Traceback (most recent call last):
  File "driver.py", line 100, in <module>
    parsed_html = BeautifulSoup(html, 'html5lib')
  File "/Users/ME/src/github/LinuxAcademy-DL/venv/lib/python3.7/site-packages/bs4/__init__.py", line 245, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?
```

**Comment by RahulShaw** [comment]
Please run `pip install html5lib`
Moreover, I've updated requirement.txt. Thanks for pointing it out.

**Comment by RahulShaw** [comment]
Please run `pip install html5lib`
Moreover, I've updated requirements.txt. Thanks for pointing it out.

**Comment by lyricnz** [comment]
Thanks.

**Comment by lyricnz** [comment]
I've got a few more improvements that I'll be making on my fork.  Any
interest in taking feature/cleanup changes?
