### ISSUE TITLE
Invalid Syntax Errors

### ISSUE THREAD

**Issue by adamwoolhether** [RahulShaw/LinuxAcademy-DL#38]
Getting errors while running the program:
File "driver.py", line 36
  File "driver.py", line 36
    f'FFmpeg not found. For help, please visit: https://www.google.com/search?q=install%20ffmpeg%20on%20{platform.system()})',
                                                                                       ^
Resolve this and then receive:
  
  File "driver.py", line 48
    chrome_options.add_argument(f'user-agent={user_agent}')

**Comment by RahulShaw** [comment]
Can you please help me with the stack trace?

**Comment by ghost** [comment]
@adamwoolhether Hi, could you please let me know how you solved the "f'FFmpeg not found. " error?

I installed in turn ffmpeg 3.x / 4.x, made sure it can run from anywhere, binary location is added to $PATH and yet I still get this error.

**Comment by adamwoolhether** [comment]
> Can you please help me with the stack trace?

Hi, I think there was just an issue with my default python interpreter. I got it working. Thanks for the response!

**Comment by adamwoolhether** [comment]
> @adamwoolhether Hi, could you please let me know how you solved the "f'FFmpeg not found. " error?
> 
> I installed in turn ffmpeg 3.x / 4.x, made sure it can run from anywhere, binary location is added to $PATH and yet I still get this error.
Where does FFmpeg point to?

$ which FFmpeg

which version of python is being called when you use python in cli? for me, only python3 would work.

**Comment by ghost** [comment]
I got it working. Had to do a pip3 install for all the modules and then run the script with p3. Plus there were a few minor syntax errors. All good now thx.
