### ISSUE TITLE
downloading not working, error Unsupported URL

### ISSUE THREAD

**Issue by arm82** [RahulShaw/LinuxAcademy-DL#40]
This is log

Executing for https://linuxacademy.com/cp/modules/view/id/314
* Trying to log in ... *
~ Logged in! ~
Getting lesson links...
Course name detected as Docker - Deep Dive
Enumerating links and sources ...
Commencing download ...
Downloading: About This Course ... [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.3-2, ffprobe 4.3-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unsupported URL: https://linuxacademy.com/cp/ssologin
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3151, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://linuxacademy.com/cp/ssologin

ERROR: Unsupported URL: https://linuxacademy.com/cp/ssologin

**Comment by Babadook007** [comment]
Has to be issues with cookies.txt .. Use prescribed plugin by Developer..

**Comment by RahulShaw** [comment]
I agree with @Babadook007, please update the cookies.txt file using this extension https://bit.ly/GoogleChrome-GetCookiesTxt and follow the instructions laid out here - https://github.com/RahulShaw/LinuxAcademy-DL#usage

**Comment by Babadook007** [comment]
@RahulShaw  I made a minor edit in my copy of driver.py -
of - Taking try catch block inside for loop..  (with continue loop on exception) It helped me to download rest videos even if some video in middle failed...
eg - I was getting error at 63rd video of total 80 videos. -
Downloading: Managed Identity ... ERROR: unable to download video data: HTTP Error 400: Bad Request
ERROR: unable to download video data: HTTP Error 400: Bad Request
Downloading failed. Perhaps, the cookies have expired.

After moving try catch inside for loop.. I'm able to download rest ( 64-80).. earlier on exception it was coming out of program.

something you would consider to do more elegantly maybe in your next release?

**Comment by adil-arif** [comment]
@Babadook007 I am having the same issue. Can you tell me what changes did you make to the code to get it working?

**Comment by adil-arif** [comment]
I figured it out. Changed 

```
try:
    for index, url in enumerate(urls, start=0):
        temp_list = [urls[index]]
        serial = str(index + 1)
        print(f'Downloading: {lessons[index]} ... ', end='', flush=True)
        ydl_opts = {
            'cookiefile': 'cookies.txt',
            'force_generic_extractor': True,
            'outtmpl': os.getcwd() + os.path.sep + title + os.path.sep + serial + '. ' + re.sub('[?/:]', '',
                                                                                                lessons[
                                                                                                    index]) + '.%(ext)s',
            'sleep_interval': 10,
            'retries': 10,
            'allsubtitles': True,
            'verbose': False,
            'quiet': True,
            'writesubtitles': True,
            'no_warnings': True
        }
        with youtube_dl.YoutubeDL(ydl_opts) as ydl:
            ydl.download(temp_list)
            temp_list.clear()
            print('\033[92m[Done \u2713]\033[0m')

    print('\n\033[92m** Downloads completed! **\033[0m\n')
except Exception as e:
    print(e)
    print('Downloading failed. Perhaps, the cookies have expired.')
```

to 

```
 for index, url in enumerate(urls, start=0):
    try:
        temp_list = [urls[index]]
        serial = str(index + 1)
        print(f'Downloading: {lessons[index]} ... ', end='', flush=True)
        ydl_opts = {
            'cookiefile': 'cookies.txt',
            'force_generic_extractor': True,
            'outtmpl': os.getcwd() + os.path.sep + title + os.path.sep + serial + '. ' + re.sub('[?/:]', '',
                                                                                                lessons[
                                                                                                    index]) + '.%(ext)s',
            'sleep_interval': 10,
            'retries': 10,
            'allsubtitles': True,
            'verbose': False,
            'quiet': True,
            'writesubtitles': True,
            'no_warnings': True
        }
        with youtube_dl.YoutubeDL(ydl_opts) as ydl:
            ydl.download(temp_list)
            temp_list.clear()
            print('\033[92m[Done \u2713]\033[0m')

    except Exception as e:
           print(e)
           print('Downloading failed. Perhaps, the cookies have expired.')

print('\n\033[92m** Downloads completed! **\033[0m\n')
```
