### ISSUE TITLE
charmap' codec can't encode character '\u2713 Windows

### ISSUE THREAD

**Issue by mavericksrini** [RahulShaw/LinuxAcademy-DL#45]
Executing for https://linuxacademy.com/cp/modules/view/id/432
* Trying to log in ... *
~ Logged in! ~
Getting lesson links...
Course name detected as Managing Microsoft Azure Applications and Infrastructure with Terraform
Enumerating links and sources ...
Commencing download ...
Downloading: An Important Note About A Cloud Guru and Linux Academy Courses ... 'charmap' codec can't encode character '\u2713' in position 11: character maps to <undefined>
Downloading failed. Perhaps, the cookies have expired.

**Comment by ArjonBu** [comment]
It looks like it's failing for any course that has this first lesson: 
**An Important Note About A Cloud Guru and Linux Academy Courses**

**Comment by RahulShaw** [comment]
@ArjonBu - I recently downloaded a course that had the aforesaid lesson and I didn't encounter the error.

**Comment by babarsumit93** [comment]
@RahulShaw: i'm also getting same error, what is the resolution for this issue?
