### ISSUE TITLE
New home page, can't authenticate

### ISSUE THREAD

**Issue by Squadz** [RahulShaw/LinuxAcademy-DL#46]
Hey,

Very nice and useful script ! 

Unfortunately it's not working anymore, since their homepage has changed ("Linux Academy and A Cloud Guru are now ONE")

I tried to redirect to "https://linuxacademy.com/cp/", however I'm getting a message from Selenium saying the field username/password are not interactible :-/ Any ideas ?

**Comment by RahulShaw** [comment]
This is now fixed!
