### ISSUE TITLE
Downloading: An Important Note About A Cloud Guru and Linux Academy Courses ... 

### ISSUE THREAD

**Issue by PrynsTag** [RahulShaw/LinuxAcademy-DL#47]
Executing for https://linuxacademy.com/cp/modules/view/id/432
* Trying to log in ... *
←[92m~ Logged in! ~←[0m
Getting lesson links...
Course name detected as Managing Microsoft Azure Applications and Infrastructure with Terraform
Enumerating links and sources ...
Commencing download ...
Downloading: An Important Note About A Cloud Guru and Linux Academy Courses ... 
ERROR: Unsupported URL: https://linux
academy.com/cp/ssologin
ERROR: Unsupported URL: https://linuxacademy.com/cp/ssologin
Downloading failed. Perhaps, the cookies have expired.

I already did the mentioned solution but still occurs for every course I download

**Comment by DevopsVlogger** [comment]
Hello , I get the same error, looks like you can only down the courses which you have either purchased or part of community courses..

**Comment by PrynsTag** [comment]
Sorry for the late response. I think your right, that is the last day of my subscription in Linux Academy. I might have not seen it prior to downloading.
