### ISSUE TITLE
failed to log in 

### ISSUE THREAD

**Issue by mariuszzab** [RahulShaw/LinuxAcademy-DL#52]
Hi, 
driver.py line 92 raised the exception that i cant login due to bad credentials. Checked double and tripple and inserting the correct ones. Do have somebody a clue what could be the reason ?

**Comment by tripperaf** [comment]
I think  they again changed login auth methods

**Comment by RahulShaw** [comment]
@mariuszzab - I just checked and things look okay. I'm afraid there's something wrong at your end, perhaps a slow internet connection or high page load time. 
Please increase the wait time on line number 85 from 30 to 60 (or more, incrementally).

@tripperaf  - Nope. Fortunately, the login methods are unchanged.
